name: Build Sky Hopper 2

name: Build Sky Hopper 2

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar código
        uses: actions/checkout@v4

      - name: Configurar Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Preparar Android SDK
        run: |
          echo "ANDROID_HOME=$ANDROID_HOME"
          yes | sdkmanager --licenses || true
          sdkmanager "platforms;android-36" "build-tools;36.0.0"

      - name: Dar permissão ao Gradle
        run: chmod +x gradlew

      - name: Gerar AAB
        run: ./gradlew bundleRelease

      - name: Salvar AAB
        uses: actions/upload-artifact@v4
        with:
          name: SkyHopper2-AAB
          path: app/build/outputs/bundle/release/*.aab
